name: Prerelease (dev)

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true

      - name: Generate tag
        id: tag
        shell: bash
        run: |
          echo "TAG_NAME=dev-$(date +'%Y%m%d-%H%M')-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build
        run: python ./release.py
        env:
          CGO_ENABLED: '0'

      - name: Publish prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Dev ${{ env.TAG_NAME }}"
          files: './release/mosdns*.zip'
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
